set(PROJECT_DEPS)
set(PROJECT_DEPS_INCLUDES)

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)

list(APPEND PROJECT_DEPS ${CMAKE_THREAD_LIBS_INIT})

find_package(Boost COMPONENTS system REQUIRED)
list(APPEND PROJECT_DEPS_INCLUDES ${Boost_INCLUDE_DIR})
list(APPEND PROJECT_DEPS ${Boost_LIBRARIES})