set(PROJECT_DEPS)
set(PROJECT_DEPS_INCLUDES)

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)

list(APPEND PROJECT_DEPS ${CMAKE_THREAD_LIBS_INIT})

find_package(Tensorflow REQUIRED)
list(APPEND PROJECT_DEPS_INCLUDES ${Tensorflow_INCLUDE_DIRS})
list(APPEND PROJECT_DEPS ${Tensorflow_LIBRARIES})